# Generated by Django 5.0.6 on 2024-07-22 17:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("S", "Sell"), ("A", "Auction")],
                        default="S",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the property", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the property", null=True
                    ),
                ),
                (
                    "rooms",
                    models.PositiveIntegerField(
                        default=1, help_text="How many rooms total"
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of bedrooms"
                    ),
                ),
                (
                    "bathrooms",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of bathrooms"
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        default=0, help_text="Size of the house in square meters"
                    ),
                ),
                (
                    "architectural_style",
                    models.CharField(
                        blank=True,
                        default="Not specified",
                        help_text="Add the style of the house",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Video of the property (optional)",
                        upload_to="videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                            )
                        ],
                    ),
                ),
                (
                    "floor_plans",
                    models.ImageField(blank=True, help_text="Optional", upload_to=""),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="realestate.estate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForSaleEstate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.estate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnAuctionEstate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starting_price", models.PositiveIntegerField(default=0)),
                ("asking_price", models.PositiveIntegerField(default=0)),
                ("sold_for", models.PositiveIntegerField(blank=True, null=True)),
                ("starting_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(auto_now_add=True)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.estate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bidding_sum", models.PositiveIntegerField(default=1000)),
                ("bidding_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.onauctionestate",
                    ),
                ),
            ],
        ),
    ]
