# Generated by Django 5.0.6 on 2024-07-13 19:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("S", "Sell"), ("A", "Auction")],
                        default="S",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("rooms", models.PositiveIntegerField(default=1)),
                ("bedrooms", models.PositiveIntegerField(default=1)),
                ("bathrooms", models.PositiveIntegerField(default=1)),
                ("size", models.PositiveIntegerField(default=0)),
                ("architectural_style", models.CharField(max_length=255)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        upload_to="videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                            )
                        ],
                    ),
                ),
                ("floor_plans", models.ImageField(blank=True, upload_to="")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="realestate.estate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForSaleEstate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.estate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnAuctionEstate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("starting_price", models.PositiveIntegerField(default=0)),
                (
                    "asking_price",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("bidding_step", models.PositiveIntegerField(default=1000)),
                (
                    "current_price",
                    models.PositiveIntegerField(
                        default=models.PositiveIntegerField(default=0)
                    ),
                ),
                (
                    "bidding_price",
                    models.PositiveIntegerField(
                        default=models.PositiveIntegerField(
                            default=models.PositiveIntegerField(default=0)
                        )
                    ),
                ),
                ("end_date", models.DateTimeField(auto_now_add=True)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realestate.estate",
                    ),
                ),
            ],
        ),
    ]
