# Generated by Django 5.0.6 on 2024-07-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realestate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estate",
            name="type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("villa", "Villa"),
                    ("townhouse", "Townhouse"),
                    ("mansion", "Mansion"),
                    ("duplex", "Duplex"),
                    ("castle", "Castle"),
                    ("loft", "Loft"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Estate type",
            ),
        ),
    ]
