# Generated by Django 5.0.6 on 2024-07-24 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='category',
            field=models.CharField(choices=[('sell', 'Sell'), ('auction', 'Auction')], default='Sell', help_text='For sale or on auction'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='architectural_style',
            field=models.CharField(blank=True, default='Not specified', help_text='Style of the house', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='estate',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='estate',
            name='floor_plans',
            field=models.ImageField(blank=True, help_text='optional', upload_to=''),
        ),
        migrations.AlterField(
            model_name='estate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='estate',
            name='rooms',
            field=models.PositiveIntegerField(default=1, help_text='Rooms in total'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='video',
            field=models.FileField(blank=True, help_text='optional', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='onauctionestate',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
